<#
    .SYNOPSIS
    Applies tags to VMs and their RGs.

    .DESCRIPTION
    The script loops over the VM list from the CSV file 
    and applies tags specified in said CSV on Resource Group and Virtual Machine level 
    based on the column preffix values.

    .PARAMETER InputFilePath
    Specifies the name and path to the CSV-based input file containing a list of VMs and the tags to be applied, 
    which are denoted by "vmTag_*" preffix for Virtual Machine resource level tags 
    and by "rgTag_*" for Resource Group resource level tags.

    .PARAMETER OutputPath
    Specifies the path for any output files generated by this script. By default,
    MonthlyUpdates.ps1 generates a name from the date and time it runs, and
    saves the output in the local directory.

    .EXAMPLE
    PS> .\ApplyTags.ps1

    .EXAMPLE
    PS> .\ApplyTags.ps1 -InputFilePath .\someOther.csv
#>

param (
    [string]
    $InputFilePath = ".\vms.csv", 
    
    [string]
    $OutputPath = ".\Logs"
)

